[script:tde_detection_converter]
match = /tde_detection_converter
script = tde_converter_rest.py
scripttype = persist
handler = tde_converter_rest.DetectionConverterHandler
python.version = python3
requireAuthentication = true
passSystemAuth = false
passSession = true
output_modes = json
passHttpHeaders = false
passPayload = true
